#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
# persist-appearance.sh — animations/input overrides generated by the panel.
#
# Port of persist-hypr.sh. The CLI and the settings.json keys are unchanged;
# only the destination/format is compositor-neutral:
#
#   Hyprland: writes Lua modules in ~/.config/hypr/config/ (loaded at the end
#             of the Lua config, so they always win) and runs `hyprctl reload`.
#   niri:     writes KDL includes in ~/.config/niri/generated/ and reloads
#             with `niri msg action load-config-file`.
#
# Usage:
#   persist-appearance.sh animations <enabled 0|1> <speed_multiplier>
#   persist-appearance.sh input <sensitivity> <accel_profile> <tap 0|1> <natural 0|1> <dwt 0|1>
#
# Environment:
#   HYPR_CONFIG_DIR    Hyprland output dir (default ~/.config/hypr/config)
#   NIRI_GENERATED_DIR niri output dir   (default ~/.config/niri/generated)
#   HYPR_NO_RELOAD=1   skip `hyprctl reload` (tests)
#   NIRI_NO_RELOAD=1   skip `niri msg action load-config-file` (tests)
#
# Merge note (Hyprland): hl.config merges partial tables, so user-input.lua
# omits kb_layout/kb_options/follow_mouse (kept in settings.lua). Under niri
# the generated `input {}` include is expected to be the only input source in
# the niri config tree; see docs/overlay.md.
# ═══════════════════════════════════════════════════════════════════════════

set -u

desktop="$(printf '%s' "${XDG_CURRENT_DESKTOP:-}" | tr '[:upper:]' '[:lower:]')"
case "$desktop" in
    *niri*) NIRI=1 ;;
    *)      NIRI=0 ;;
esac

if [[ "$NIRI" == "1" ]]; then
    OUT_DIR="${NIRI_GENERATED_DIR:-$HOME/.config/niri/generated}"
else
    OUT_DIR="${HYPR_CONFIG_DIR:-$HOME/.config/hypr/config}"
fi

MODE="${1:-}"

mkdir -p "$OUT_DIR" || exit 1

# round1 <base> <mult> -> "3.6" / "6" / "60" (1 decimal, no trailing .0).
round1() {
    awk -v b="$1" -v m="$2" 'BEGIN {
        v = b * m * 10;
        n = int(v + (v < 0 ? -0.5 : 0.5));
        if (n % 10 == 0) printf "%d", n / 10;
        else printf "%.1f", n / 10;
    }'
}

# lua_bool <0|1> -> true/false
lua_bool() { if [[ "$1" == "1" ]]; then printf "true"; else printf "false"; fi; }

# kdl_bool <0|1> -> true/false
kdl_bool() { if [[ "$1" == "1" ]]; then printf "true"; else printf "false"; fi; }

# Atomic write: stdin -> destination.
write_atomic() {
    local dest="$1" tmp
    tmp="$(mktemp "$OUT_DIR/.persist-appearance.XXXXXX")" || return 1
    cat > "$tmp" || { rm -f "$tmp"; return 1; }
    mv -f "$tmp" "$dest" || { rm -f "$tmp"; return 1; }
}

# luac -p gate: if it does not compile, drop it and fail.
validate_or_drop() {
    local file="$1"
    if ! luac -p "$file" >/dev/null 2>&1; then
        echo "persist-appearance: luac -p failed, dropping $file" >&2
        rm -f "$file"
        exit 1
    fi
}

reload_compositor() {
    if [[ "$NIRI" == "1" ]]; then
        [[ "${NIRI_NO_RELOAD:-0}" == "1" ]] && return 0
        niri msg action load-config-file >/dev/null 2>&1 || true
        if command -v notify-send >/dev/null 2>&1; then
            notify-send -t 1500 "niri" "Panel overrides applied (reload)" >/dev/null 2>&1 || true
        fi
    else
        [[ "${HYPR_NO_RELOAD:-0}" == "1" ]] && return 0
        hyprctl reload >/dev/null 2>&1 || true
        if command -v notify-send >/dev/null 2>&1; then
            notify-send -t 1500 "Hyprland" "Panel overrides applied (reload)" >/dev/null 2>&1 || true
        fi
    fi
}

# ─── animations ────────────────────────────────────────────────────────────
run_animations_hypr() {
    local enabled="$1" speed="$2" out
    out="$OUT_DIR/user-animations.lua"
    {
        echo "-- Auto-generated by the Settings panel. Do not edit manually."
        echo "hl.config({ animations = { enabled = $(lua_bool "$enabled") } })"
        echo ""
        echo "-- The 6 curves live in animations.lua (NOT redefined here): only the"
        echo "-- 12 animations are re-declared with the speed-scaled value."
        printf 'hl.animation({ leaf = "windowsIn",  enabled = true, speed = %s, bezier = "overshot", style = "popin 80%%" })\n' "$(round1 6 "$speed")"
        printf 'hl.animation({ leaf = "windowsOut", enabled = true, speed = %s, bezier = "easeOutExpo", style = "popin 80%%" })\n' "$(round1 5 "$speed")"
        printf 'hl.animation({ leaf = "windowsMove", enabled = true, speed = %s, bezier = "overshot" })\n' "$(round1 5 "$speed")"
        echo ""
        printf 'hl.animation({ leaf = "fadeIn",     enabled = true, speed = %s, bezier = "easeOutExpo" })\n' "$(round1 4 "$speed")"
        printf 'hl.animation({ leaf = "fadeOut",    enabled = true, speed = %s, bezier = "easeOutExpo" })\n' "$(round1 4 "$speed")"
        printf 'hl.animation({ leaf = "fadeSwitch", enabled = true, speed = %s, bezier = "easeOutExpo" })\n' "$(round1 4 "$speed")"
        printf 'hl.animation({ leaf = "fadeShadow", enabled = true, speed = %s, bezier = "easeOutExpo" })\n' "$(round1 4 "$speed")"
        printf 'hl.animation({ leaf = "fadeDim",    enabled = true, speed = %s, bezier = "easeOutExpo" })\n' "$(round1 4 "$speed")"
        echo ""
        printf 'hl.animation({ leaf = "border", enabled = true, speed = %s, bezier = "smooth" })\n' "$(round1 10 "$speed")"
        printf 'hl.animation({ leaf = "borderangle", enabled = true, speed = %s, bezier = "linear", style = "loop" })\n' "$(round1 100 "$speed")"
        echo ""
        printf 'hl.animation({ leaf = "workspaces", enabled = true, speed = %s, bezier = "overshot", style = "slide" })\n' "$(round1 6 "$speed")"
        printf 'hl.animation({ leaf = "specialWorkspace", enabled = true, speed = %s, bezier = "overshot", style = "slidevert" })\n' "$(round1 6 "$speed")"
    } | write_atomic "$out" || exit 1
    validate_or_drop "$out"
    echo "user-animations.lua saved (enabled=$enabled speed=$speed)"
}

run_animations_niri() {
    local enabled="$1" speed="$2" out
    out="$OUT_DIR/user-animations.kdl"
    if [[ "$enabled" != "1" ]]; then
        {
            echo "// Auto-generated by the Settings panel. Do not edit manually."
            echo "animations {"
            echo "    off"
            echo "}"
        } | write_atomic "$out" || exit 1
    else
        # Hyprland leaf names are remapped to niri animations:
        #   windowsIn/windowsOut -> window-open/window-close (easing, scaled)
        #   windowsMove          -> window-movement/window-resize (spring)
        #   workspaces           -> workspace-switch (spring)
        #   borderangle, fade*   -> no niri equivalent, covered by global speed.
        {
            echo "// Auto-generated by the Settings panel. Do not edit manually."
            echo "// Hyprland leaf names remapped to niri animation nodes."
            echo "animations {"
            printf '    window-open {\n        duration-ms %s\n        curve "ease-out-expo"\n    }\n' "$(round1 150 "$speed")"
            printf '    window-close {\n        duration-ms %s\n        curve "ease-out-quad"\n    }\n' "$(round1 150 "$speed")"
            echo "    workspace-switch {"
            echo "        spring damping-ratio=1.0 stiffness=1000 epsilon=0.0001"
            echo "    }"
            echo "    horizontal-view-movement {"
            echo "        spring damping-ratio=1.0 stiffness=800 epsilon=0.0001"
            echo "    }"
            echo "    window-movement {"
            echo "        spring damping-ratio=1.0 stiffness=800 epsilon=0.0001"
            echo "    }"
            echo "    window-resize {"
            echo "        spring damping-ratio=1.0 stiffness=800 epsilon=0.0001"
            echo "    }"
            echo "}"
        } | write_atomic "$out" || exit 1
    fi
    if command -v niri >/dev/null 2>&1 && ! niri validate -c "$out" >/dev/null 2>&1; then
        echo "persist-appearance: niri validate failed, dropping $out" >&2
        rm -f "$out"
        exit 1
    fi
    echo "user-animations.kdl saved (enabled=$enabled speed=$speed)"
}

# ─── input ─────────────────────────────────────────────────────────────────
run_input_hypr() {
    local sens="$1" profile="$2" tap="$3" natural="$4" dwt="$5" out
    out="$OUT_DIR/user-input.lua"
    {
        echo "-- Auto-generated by the Settings panel. Do not edit manually."
        echo "-- Pointer/touchpad only: kb_layout/kb_options/follow_mouse live in"
        echo "-- settings.lua and the partial hl.config merge keeps them."
        echo "hl.config({ input = {"
        echo "    sensitivity   = $sens,"
        echo "    accel_profile = \"$profile\","
        echo "    touchpad = {"
        echo "        natural_scroll       = $(lua_bool "$natural"),"
        echo "        disable_while_typing = $(lua_bool "$dwt"),"
        echo "        tap_to_click         = $(lua_bool "$tap"),"
        echo "    },"
        echo "} })"
    } | write_atomic "$out" || exit 1
    validate_or_drop "$out"
    echo "user-input.lua saved (sens=$sens profile=$profile tap=$tap natural=$natural dwt=$dwt)"
}

run_input_niri() {
    local sens="$1" profile="$2" tap="$3" natural="$4" dwt="$5" out
    out="$OUT_DIR/user-input.kdl"
    # niri splits pointer settings per device type and uses flags for booleans.
    {
        echo "// Auto-generated by the Settings panel. Do not edit manually."
        echo "// Pointer/touchpad only; keyboard layout stays in the base niri config."
        echo "input {"
        echo "    touchpad {"
        [[ "$tap" == "1" ]] && echo "        tap"
        [[ "$natural" == "1" ]] && echo "        natural-scroll"
        [[ "$dwt" == "1" ]] && echo "        dwt"
        echo "        accel-speed $sens"
        echo "        accel-profile \"$profile\""
        echo "    }"
        echo "    mouse {"
        echo "        accel-speed $sens"
        echo "        accel-profile \"$profile\""
        echo "    }"
        echo "}"
    } | write_atomic "$out" || exit 1
    if command -v niri >/dev/null 2>&1 && ! niri validate -c "$out" >/dev/null 2>&1; then
        echo "persist-appearance: niri validate failed, dropping $out" >&2
        rm -f "$out"
        exit 1
    fi
    echo "user-input.kdl saved (sens=$sens profile=$profile tap=$tap natural=$natural dwt=$dwt)"
}

# ─── dispatch ────────────────────────────────────────────────────────────────
case "$MODE" in
    animations)
        ENABLED="${2:-1}"
        SPEED="${3:-1.0}"
        [[ "$ENABLED" == "1" ]] || ENABLED=0
        [[ "$SPEED" =~ ^[0-9]+([.][0-9]+)?$ ]] || SPEED=1.0
        [[ "$SPEED" == "0" || "$SPEED" == "0.0" ]] && SPEED=1.0
        if [[ "$NIRI" == "1" ]]; then
            run_animations_niri "$ENABLED" "$SPEED"
        else
            run_animations_hypr "$ENABLED" "$SPEED"
        fi
        reload_compositor
        ;;
    input)
        SENS="${2:-0}"
        PROFILE="${3:-flat}"
        TAP="${4:-1}"
        NATURAL="${5:-1}"
        DWT="${6:-1}"
        [[ "$SENS" =~ ^-?[0-9]+([.][0-9]+)?$ ]] || SENS=0
        case "$PROFILE" in flat|adaptive) ;; *) PROFILE=flat ;; esac
        if [[ "$NIRI" == "1" ]]; then
            run_input_niri "$SENS" "$PROFILE" "$TAP" "$NATURAL" "$DWT"
        else
            run_input_hypr "$SENS" "$PROFILE" "$TAP" "$NATURAL" "$DWT"
        fi
        reload_compositor
        ;;
    *)
        echo "usage: persist-appearance.sh animations <0|1> <speed> | persist-appearance.sh input <sensitivity> <profile> <tap> <natural> <dwt>" >&2
        exit 2
        ;;
esac
