// ═══════════════════════════════════════════════════════════════════════════
// shell · core/compositors — niri backend
//
// niri implementation of the Compositor surface. Every value is produced with
// real niri 26.04 commands (`niri msg --json ...`, `niri msg action ...`) and
// every write targets a generated KDL include under ~/.config/niri/generated
// followed by `niri msg action load-config-file`. Output shapes match
// Hyprland.qml so the bar, the palette and the monitor canvas keep working
// unchanged.
// ═══════════════════════════════════════════════════════════════════════════
import QtQuick
import Quickshell
import Quickshell.Io

QtObject {
    id: backend

    // ── data sources for the bar pollers ──────────────────────────────────
    readonly property var workspacesCommand: ["bash", "-c", "~/.config/hypr/scripts/quickshell/core/scripts/niri-workspaces.sh"]

    readonly property var keyboardCommand: ["bash", "-c",
        "niri msg --json keyboard-layouts 2>/dev/null | " +
        "jq -r 'if .names and (.names[.current_idx] != null) then .names[.current_idx] else empty end' 2>/dev/null " +
        "| sed -n 's/.*(\\([A-Za-z][A-Za-z]\\)).*/\\1/p; t; s/^\\([A-Za-z][A-Za-z]\\).*/\\1/p' " +
        "| head -n1 | tr '[:lower:]' '[:upper:]'"]

    readonly property var focusCommand: ["bash", "-c",
        "niri msg --json focused-window 2>/dev/null | " +
        "jq -r 'if . == null then empty else (.app_id + \"\\n\" + (.title // \"\")) end' 2>/dev/null"]

    // ── helpers ────────────────────────────────────────────────────────────
    function sh(cmd) { Quickshell.execDetached(["bash", "-c", cmd]); }

    // Atomic write of a generated KDL include; callers trigger the reload.
    function writeGenerated(fileName, content) {
        backend.sh(
            "mkdir -p \"$HOME/.config/niri/generated\" && " +
            "tmp=$(mktemp \"$HOME/.config/niri/generated/." + fileName + ".XXXXXX\") && " +
            "cat > \"$tmp\" <<'XSC_GEN_EOF'\n" + content + "XSC_GEN_EOF\n" +
            "mv \"$tmp\" \"$HOME/.config/niri/generated/" + fileName + "\""
        );
    }

    function reload() {
        Quickshell.execDetached(["niri", "msg", "action", "load-config-file"]);
    }

    // ── window borders: generated KDL include ──────────────────────────────
    // Width is intentionally NOT written here so theme-effects.kdl keeps
    // ownership of `border width`; this file only sets the colours.
    function kdlBorderColor(kind, spec) {
        const alpha = (spec && spec.alpha) ? String(spec.alpha) : "ee";
        const hex = String((spec && spec.hex) || "#ffffff").replace("#", "");
        const second = (spec && spec.second) ? String(spec.second).replace("#", "") : "";
        if (/^[0-9a-fA-F]{6}$/.test(second)) {
            const angle = Math.round(Number((spec && spec.angle) || 45));
            return "        " + kind + "-gradient from=\"#" + hex + alpha + "\" to=\"#" + second + alpha + "\" angle=" + angle;
        }
        return "        " + kind + "-color \"#" + hex + alpha + "\"";
    }

    function setWindowBorders(activeSpec, inactiveSpec) {
        const kdl = "// Auto-generated by the compositor backend. Do not edit manually.\n" +
            "layout {\n" +
            "    border {\n" +
            "        on\n" +
            backend.kdlBorderColor("active", activeSpec) + "\n" +
            backend.kdlBorderColor("inactive", inactiveSpec) + "\n" +
            "    }\n" +
            "    focus-ring { off }\n" +
            "}\n";
        backend.writeGenerated("borders.kdl", kdl);
        backend.reload();
    }

    function switchWorkspace(name) {
        if (name === undefined || name === null || String(name) === "") return;
        Quickshell.execDetached(["niri", "msg", "action", "focus-workspace", String(name)]);
    }

    function cycleKeyboardLayout() {
        Quickshell.execDetached(["niri", "msg", "action", "switch-layout", "next"]);
    }

    // ── neutral session actions ────────────────────────────────────────────
    // The niri stack ships the equivalent idle controller; same verbs and the
    // same ~/.config/hypr/idle-settings.json state as the Hyprland script.
    function idleMode(mode) {
        Quickshell.execDetached(["bash", Quickshell.env("HOME") + "/.config/niri/scripts/niri_idle_mode.sh", String(mode)]);
    }

    // niri shows a confirmation dialog by default; skip it so the battery
    // popup logout is as immediate as the Hyprland exit.sh path.
    function quit() {
        Quickshell.execDetached(["niri", "msg", "action", "quit", "--skip-confirmation"]);
    }

    // ── stateful monitor poller ────────────────────────────────────────────
    signal monitorsDecoded(var data)

    readonly property var displayPoller: Process {
        // Both calls in one bash invocation: the shell is line-agnostic here,
        // decodeNiri reads the combined envelope.
        command: ["bash", "-c",
            "o=$(niri msg --json outputs 2>/dev/null); [ -z \"$o\" ] && o='{}'; " +
            "f=$(niri msg --json focused-output 2>/dev/null); [ -z \"$f\" ] && f='null'; " +
            "printf '{\"outputs\":%s,\"focused\":%s}' \"$o\" \"$f\""]
        running: false
        stdout: StdioCollector {
            onStreamFinished: {
                let data = [];
                try { data = backend.decodeNiri(this.text); } catch (e) { data = []; }
                backend.monitorsDecoded(data);
            }
        }
    }

    function transformToInt(t) {
        switch (String(t)) {
            case "90": return 1;
            case "180": return 2;
            case "270": return 3;
            case "flipped": return 4;
            case "flipped-90": return 5;
            case "flipped-180": return 6;
            case "flipped-270": return 7;
            default: return 0;
        }
    }

    // Normalise `niri msg --json outputs` (+ focused-output) to the same shape
    // Config.qml already consumed from `hyprctl monitors -j`.
    function decodeNiri(text) {
        let env = JSON.parse(text);
        let outs = env.outputs || {};
        let focused = (env.focused && env.focused.name) ? env.focused.name : "";
        let names = Object.keys(outs).sort();
        let result = [];
        for (let i = 0; i < names.length; i++) {
            let name = names[i];
            let o = outs[name] || {};
            let modes = o.modes || [];
            let cur = (typeof o.current_mode === "number" && modes[o.current_mode]) ? modes[o.current_mode] : (modes[0] || {});
            let logical = (o.logical !== undefined) ? o.logical : null;
            let make = o.make || "";
            let model = o.model || "";
            let serial = (o.serial !== undefined && o.serial !== null && String(o.serial) !== "0") ? String(o.serial) : "";
            let desc = (make + " " + model + " " + serial).trim();
            let rr = (cur.refresh_rate !== undefined) ? (Number(cur.refresh_rate) / 1000) : 60;
            let avail = [];
            for (let m = 0; m < modes.length; m++) {
                let md = modes[m];
                // niri requires the refresh rate to match exactly, including
                // three decimals, so the mode string is normalised to "WxH@RHz"
                // with toFixed(3) (niri reports millihertz).
                let rate = (md.refresh_rate !== undefined) ? (Number(md.refresh_rate) / 1000) : 0;
                avail.push(md.width + "x" + md.height + "@" + rate.toFixed(3) + "Hz");
            }
            result.push({
                name: name,
                width: cur.width || 0,
                height: cur.height || 0,
                refreshRate: rr,
                x: logical ? logical.x : 0,
                y: logical ? logical.y : 0,
                scale: logical ? logical.scale : 1,
                transform: backend.transformToInt(logical ? logical.transform : "normal"),
                focused: (name === focused),
                availableModes: avail,
                description: desc,
                vrr: o.vrr_enabled === true,
                disabled: logical === null,
                mirrorOf: "none",
                colorManagementPreset: "auto",
                currentFormat: "",
                bitdepth: 8,
                sdrBrightness: 1,
                sdrSaturation: 1
            });
        }
        return result;
    }

    // ── keybind persistence (niri KDL) ─────────────────────────────────────
    function modTokens(mods) {
        if (!mods) return [];
        let out = [];
        let parts = String(mods).split("&");
        for (let i = 0; i < parts.length; i++) {
            let m = parts[i].trim().toUpperCase();
            if (m === "SUPER" || m === "MOD" || m === "WIN" || m.indexOf("SUPER") === 0) { if (out.indexOf("Mod") < 0) out.push("Mod"); }
            else if (m === "SHIFT") { if (out.indexOf("Shift") < 0) out.push("Shift"); }
            else if (m === "CTRL" || m === "CONTROL") { if (out.indexOf("Ctrl") < 0) out.push("Ctrl"); }
            else if (m === "ALT" || m === "MOD1") { if (out.indexOf("Alt") < 0) out.push("Alt"); }
        }
        return out;
    }

    function keyToken(key) {
        let k = String(key || "");
        let mouse = {
            "mouse:272": "MouseLeft", "mouse:273": "MouseRight", "mouse:274": "MouseMiddle",
            "mouse:275": "MouseForward", "mouse:276": "MouseBack"
        };
        if (mouse[k]) return mouse[k];
        if (k.indexOf("mouse:") === 0 || k.indexOf("code:") === 0) return null;
        let named = {
            "SPACE": "Space", "TAB": "Tab", "RETURN": "Return", "ENTER": "Return",
            "ESC": "Escape", "ESCAPE": "Escape", "SLASH": "Slash", "COMMA": "Comma",
            "PERIOD": "Period", "MINUS": "Minus", "EQUAL": "Equal",
            "BACKSLASH": "Backslash", "GRAVE": "Grave"
        };
        let up = k.toUpperCase();
        if (named[up]) return named[up];
        return (k.length === 1) ? k.toUpperCase() : k;
    }

    // Workspace references are an index or a name. Emit a bare number for a
    // numeric id (matching Hyprland semantics and niri's own bind examples) and
    // a quoted KDL string for a named workspace.
    function wsArg(c) {
        let s = String(c || "");
        return /^-?\d+$/.test(s) ? s : JSON.stringify(s);
    }

    function niriAction(dispatcher, command) {
        command = (command || "").trim();
        let dir = { "l": "left", "r": "right", "u": "up", "d": "down" };
        switch (dispatcher) {
            case "exec":
            case "exec-once":
                return { action: "spawn-sh", args: JSON.stringify(command), locked: true };
            case "workspace":
                if (command === "e+1") return { action: "focus-workspace-down" };
                if (command === "e-1") return { action: "focus-workspace-up" };
                if (command === "previous") return { action: "focus-workspace-previous" };
                return { action: "focus-workspace", args: backend.wsArg(command) };
            case "movetoworkspace":
                if (command === "e+1") return { action: "move-window-to-workspace-down" };
                if (command === "e-1") return { action: "move-window-to-workspace-up" };
                return { action: "move-window-to-workspace", args: backend.wsArg(command) };
            case "movewindow":
                return dir[command] ? { action: "move-column-" + dir[command] }
                                    : { action: "move-window-to-monitor", args: JSON.stringify(command) };
            case "movefocus":
                if (command === "l") return { action: "focus-column-left" };
                if (command === "r") return { action: "focus-column-right" };
                if (command === "u") return { action: "focus-window-up" };
                return { action: "focus-window-down" };
            case "togglefloating":
                return { action: "toggle-window-floating" };
            case "killactive":
                return { action: "close-window" };
            default:
                return null;
        }
    }

    function persistKeybinds(bindsArray) {
        let lines = [];
        lines.push("// Auto-generated by the QuickShell settings panel. Do not edit manually.");
        lines.push("binds {");
        let order = [];
        let map = {};
        for (let i = 0; i < bindsArray.length; i++) {
            let b = bindsArray[i];
            if (!b.key || !b.dispatcher) continue;
            let key = backend.keyToken(b.key);
            if (!key) { lines.push("    // [skipped] unsupported key " + b.key); continue; }
            let act = backend.niriAction(b.dispatcher, b.command);
            if (!act) { lines.push("    // [skipped] " + b.dispatcher + " (no niri equivalent)"); continue; }
            let hot = backend.modTokens(b.mods).concat([key]).join("+");
            let action = act.action + (act.args ? " " + act.args : "") + ";";
            let flags = act.locked ? " allow-when-locked=true" : "";
            let line = "    " + hot + flags + " { " + action + " }";
            if (map[hot] === undefined) order.push(hot);
            map[hot] = line;
        }
        for (let j = 0; j < order.length; j++) lines.push(map[order[j]]);
        lines.push("}");
        lines.push("");
        backend.writeGenerated("user-binds.kdl", lines.join("\n"));
        backend.reload();
    }

    function persistStartup(startupArray) {
        let lines = [];
        lines.push("// Auto-generated by the QuickShell settings panel. Do not edit manually.");
        for (let i = 0; i < startupArray.length; i++) {
            let s = startupArray[i];
            if (!s.command || !s.command.trim()) continue;
            lines.push("spawn-sh-at-startup " + JSON.stringify(s.command.trim()));
        }
        lines.push("");
        backend.writeGenerated("user-startup.kdl", lines.join("\n"));
        backend.reload();
    }

    // ── monitor apply / reset ─────────────────────────────────────────────
    function niriMode(hypMode) {
        if (!hypMode) return null;
        let m = String(hypMode).match(/^(\d+x\d+)@([\d.]+)Hz$/);
        return m ? (m[1] + "@" + m[2]) : null; // highrr/preferred -> omit, niri picks
    }

    function intToTransform(t) {
        let map = { 0: "normal", 1: "90", 2: "180", 3: "270", 4: "flipped", 5: "flipped-90", 6: "flipped-180", 7: "flipped-270" };
        return map[t] || "normal";
    }

    // niri matches an output by connector name or by "make model serial"
    // (which survives connector renames). Only use the EDID form when all
    // three parts are present; otherwise fall back to the connector name.
    function outputKey(d) {
        let desc = String(d.description || "").trim();
        if (desc !== "" && desc.split(/\s+/).length >= 3) return desc;
        return d.name;
    }

    function kdlOutput(d) {
        let key = backend.outputKey(d);
        let lines = ["output " + JSON.stringify(key) + " {"];
        if (d.disabled === true) {
            lines.push("    off");
        } else {
            let mode = backend.niriMode(d.mode);
            if (mode) lines.push("    mode " + JSON.stringify(mode));
            lines.push("    scale " + d.scale);
            let tf = backend.intToTransform(d.transform);
            if (tf !== "normal") lines.push("    transform " + JSON.stringify(tf));
            lines.push("    position x=" + d.x + " y=" + d.y);
            if (d.vrr === 2) lines.push("    variable-refresh-rate on-demand=true");
            else if (d.vrr === 1) lines.push("    variable-refresh-rate");
        }
        lines.push("}");
        return lines.join("\n");
    }

    function applyMonitors(descriptors, displayConfigText) {
        let blocks = [];
        for (let i = 0; i < descriptors.length; i++) blocks.push(backend.kdlOutput(descriptors[i]));
        let kdl = "// Auto-generated by the compositor backend. Do not edit manually.\n" + blocks.join("\n") + "\n";
        backend.writeGenerated("outputs.kdl", kdl);
        backend.reload();
    }

    function resetMonitors() {
        backend.sh("rm -f \"$HOME/.config/niri/generated/outputs.kdl\" && niri msg action load-config-file >/dev/null 2>&1");
    }

    // ── neutral monitor / version / launch helpers ─────────────────────────
    // niri has no submaps: callers must gate the controls on this flag.
    readonly property bool hasSubmaps: false

    readonly property var monitorListCommand: ["bash", "-c",
        "o=$(niri msg --json outputs 2>/dev/null); [ -z \"$o\" ] && o='{}'; " +
        "f=$(niri msg --json focused-output 2>/dev/null); [ -z \"$f\" ] && f='null'; " +
        "printf '{\"outputs\":%s,\"focused\":%s}' \"$o\" \"$f\""]

    readonly property var versionCommand: ["niri", "msg", "--json", "version"]

    signal monitorListReady(var list)
    signal versionReady(var version)

    property var _monitorCache: []
    property string _versionCache: ""

    // The combined outputs+focused envelope is exactly what decodeNiri reads.
    function monitorsFromOutput(text) { return backend.decodeNiri(text); }

    readonly property var _monitorProc: Process {
        command: backend.monitorListCommand
        running: false
        stdout: StdioCollector {
            onStreamFinished: {
                let list = [];
                try { list = backend.monitorsFromOutput(this.text); } catch (e) { list = []; }
                backend._monitorCache = list;
                backend.monitorListReady(list);
            }
        }
    }

    function monitorList() { return backend._monitorCache; }
    function refreshMonitorList() { backend._monitorProc.running = true; }

    function versionFromOutput(text) {
        try {
            let d = JSON.parse(text);
            return String(d.compositor || d.cli || "");
        } catch (e) { return ""; }
    }

    readonly property var _versionProc: Process {
        command: backend.versionCommand
        running: false
        stdout: StdioCollector {
            onStreamFinished: {
                backend._versionCache = backend.versionFromOutput(this.text);
                backend.versionReady(backend._versionCache);
            }
        }
    }

    function compositorVersion() { return backend._versionCache; }
    function refreshCompositorVersion() { backend._versionProc.running = true; }

    // Global display scale: niri's runtime setter is per output and temporary,
    // so apply it to every output (matching scale-menu.sh's "everything"
    // semantics) and record it in settings.json so the next applyMonitors
    // materialises it into generated/outputs.kdl.
    function applyMonitorScale(name, scale) {
        let s = String(scale);
        if (!/^[0-9.]+$/.test(s)) return;
        let cmd =
            "mkdir -p \"$HOME/.config/hypr\"; " +
            "if [ -f \"$HOME/.config/hypr/settings.json\" ]; then " +
            "tmp=$(mktemp \"$HOME/.config/hypr/settings.json.tmp.XXXXXX\") && " +
            "jq --argjson s " + s + " '.monitors = ((.monitors // []) | map(.scale = $s))' " +
            "\"$HOME/.config/hypr/settings.json\" > \"$tmp\" && mv \"$tmp\" \"$HOME/.config/hypr/settings.json\"; fi; " +
            "for o in $(niri msg --json outputs 2>/dev/null | jq -r 'keys[]' 2>/dev/null); do " +
            "niri msg output \"$o\" scale " + s + " >/dev/null 2>&1; done";
        backend.sh(cmd);
    }

    // Apply one neutral descriptor live through `niri msg output` (temporary;
    // persistence stays with Config.applyMonitors -> outputs.kdl).
    function applyMonitorConfig(d) {
        if (!d || !d.name) return;
        let key = backend.outputKey(d);
        let parts = [];
        if (d.disabled === true) {
            parts.push("off");
        } else {
            let mode = backend.niriMode(d.mode);
            if (mode) parts.push("mode " + JSON.stringify(mode));
            if (d.scale !== undefined) parts.push("scale " + d.scale);
            if (d.transform !== undefined) parts.push("transform " + JSON.stringify(backend.intToTransform(d.transform)));
            if (d.x !== undefined && d.y !== undefined) parts.push("position set " + d.x + " " + d.y);
            if (d.vrr === 2) parts.push("vrr on --on-demand");
            else if (d.vrr === 1) parts.push("vrr on");
        }
        if (parts.length === 0) return;
        let cmd = "";
        for (let i = 0; i < parts.length; i++) {
            cmd += "niri msg output " + JSON.stringify(key) + " " + parts[i] + " >/dev/null 2>&1; ";
        }
        backend.sh(cmd);
    }

    // Spawn with no compositor involvement.
    function execApp(commandString) {
        if (!commandString) return;
        Quickshell.execDetached(["bash", "-c", commandString]);
    }

    // niri has no submaps; recording a key needs no compositor change.
    function setSubmap(name) { }
}
